import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { metroLines, metroStationLines, metrobusLines, metrobusStationLines, type Transport } from '@meperdienelmetro/core';
import { useApp } from '../src/app-state';
import { StationDetail } from '../src/components/StationDetail';
import { TransitMap } from '../src/components/TransitMap';

export default function CatalogScreen(){const {theme,t,mode}=useApp();const [transport,setTransport]=useState<Transport>('metro');const [open,setOpen]=useState<string|null>(null);const [station,setStation]=useState<string|null>(null);const lines=transport==='metro'?metroLines:metrobusLines;const stationLines=transport==='metro'?metroStationLines:metrobusStationLines;
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.colors.background}]}><ScrollView contentContainerStyle={styles.page}><Text style={[styles.eyebrow,{color:theme.colors.accent}]}>{t.catalog}</Text><Text style={[styles.title,{color:theme.colors.text}]}>{t.allLines}</Text><Text style={[styles.copy,{color:theme.colors.muted}]}>{t.selectLine}</Text><View style={[styles.tabs,{backgroundColor:mode==='dark'?'#20362D':'#E9ECE6'}]}>{(['metro','metrobus'] as const).map(item=><Pressable key={item} onPress={()=>{setTransport(item);setOpen(null)}} style={[styles.tab,transport===item&&{backgroundColor:theme.colors.surface}]}><Text style={{color:transport===item?theme.colors.text:theme.colors.muted,fontWeight:'800'}}>{item==='metro'?'Metro':'Metrobús'}</Text></Pressable>)}</View><TransitMap lines={lines} title={t.map}/>{lines.map(line=>{const expanded=open===line.id;return <View key={line.id} style={[styles.lineCard,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Pressable onPress={()=>setOpen(expanded?null:line.id)} style={styles.lineHead}><View style={[styles.badge,{backgroundColor:line.color}]}><Text style={styles.badgeText}>{line.id}</Text></View><View style={{flex:1}}><Text style={[styles.lineTitle,{color:theme.colors.text}]}>{t.line} {line.id}</Text><Text style={[styles.lineMeta,{color:theme.colors.muted}]}>{line.stations[0]} — {line.stations.at(-1)}</Text></View><Text style={{color:theme.colors.accent,fontSize:20}}>{expanded?'−':'+'}</Text></Pressable>{expanded&&<View style={[styles.stationList,{borderColor:theme.colors.border}]}>{line.stations.map((name,index)=><Pressable key={`${name}-${index}`} style={styles.station} onPress={()=>setStation(name)}><View style={[styles.stationDot,{backgroundColor:line.color}]}/><Text style={[styles.stationText,{color:theme.colors.text}]}>{name}</Text></Pressable>)}</View>}</View>})}<StationDetail station={station} lines={station?stationLines(station):[]} onClose={()=>setStation(null)}/></ScrollView></SafeAreaView>;}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:20,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{fontSize:30,fontWeight:'900',marginTop:7},copy:{fontSize:14,lineHeight:20,marginTop:8},tabs:{flexDirection:'row',padding:4,borderRadius:16,marginTop:20},tab:{flex:1,alignItems:'center',paddingVertical:11,borderRadius:13},lineCard:{marginTop:10,borderWidth:1,borderRadius:18,overflow:'hidden'},lineHead:{flexDirection:'row',alignItems:'center',gap:12,padding:15},badge:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontWeight:'900'},lineTitle:{fontSize:16,fontWeight:'900'},lineMeta:{fontSize:12,marginTop:3},stationList:{borderTopWidth:1,padding:12},station:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:8},stationDot:{width:9,height:9,borderRadius:5},stationText:{fontSize:14,fontWeight:'700'}});
