import { useState } from 'react';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { metroLines, metrobusLines, type RouteMode, type Transport } from '@meperdienelmetro/core';
import { StationPicker } from '../src/components/StationPicker';
import { useApp } from '../src/app-state';

export default function HomeScreen(){
 const {theme,t,mode:themeMode}=useApp(); const [transport,setTransport]=useState<Transport>('metro'); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [mode,setMode]=useState<RouteMode>('fast');
 const lines=transport==='metro'?metroLines:metrobusLines; const same=Boolean(from&&to&&from===to); const ready=Boolean(from&&to&&!same);
 const switchTransport=(next:Transport)=>{setTransport(next);setFrom('');setTo('')};
 const search=()=>{if(ready)router.push({pathname:'/route',params:{transport,from,to,mode}})};
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.colors.background}]}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">
  <View style={styles.brandRow}><Text style={[styles.brand,{color:theme.colors.text}]}>{transport==='metro'?t.brandMetro:t.brandMetrobus}<Text style={{color:theme.colors.accent}}>.</Text></Text><View style={[styles.offline,{backgroundColor:theme.colors.accentSoft}]}><Text style={[styles.offlineText,{color:theme.colors.success}]}>OFFLINE</Text></View></View>
  <View style={styles.quickNav}><Pressable onPress={()=>router.push('/catalog')}><Text style={[styles.quickNavText,{color:theme.colors.muted}]}>{t.catalog}</Text></Pressable><Pressable onPress={()=>router.push('/service')}><Text style={[styles.quickNavText,{color:theme.colors.muted}]}>{t.service}</Text></Pressable><Pressable onPress={()=>router.push('/settings')}><Text style={[styles.quickNavText,{color:theme.colors.muted}]}>{t.preferences}</Text></Pressable></View>
  <Text style={[styles.eyebrow,{color:theme.colors.accent}]}>{t.homeTag}</Text><Text style={[styles.title,{color:theme.colors.text}]}>{t.homeTitle}{'\n'}<Text style={{color:theme.colors.accent}}>{t.homeAccent}</Text></Text><Text style={[styles.copy,{color:theme.colors.muted}]}>{t.homeCopy}</Text>
  <View style={[styles.tabs,{backgroundColor:themeMode==='dark'?'#20362D':'#E9ECE6'}]}>{(['metro','metrobus'] as const).map(item=><Pressable key={item} onPress={()=>switchTransport(item)} style={[styles.tab,transport===item&&{backgroundColor:theme.colors.surface}]}><Text style={[styles.tabText,{color:transport===item?theme.colors.text:theme.colors.muted}]}>{item==='metro'?'Metro':'Metrobús'}</Text></Pressable>)}</View>
  <View style={[styles.card,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Text style={[styles.eyebrow,{color:theme.colors.accent}]}>{t.plan}</Text><Text style={[styles.cardTitle,{color:theme.colors.text}]}>{t.where}</Text>
   <StationPicker label={t.from} value={from} lines={lines} onChange={setFrom} placeholder={t.origin}/>
   <Pressable accessibilityRole="button" accessibilityLabel={t.swap} onPress={()=>{setFrom(to);setTo(from)}} style={[styles.swap,{borderColor:theme.colors.border,backgroundColor:theme.colors.background}]}><Text style={{color:theme.colors.accent}}>⇅  {t.swap}</Text></Pressable>
   <StationPicker label={t.to} value={to} lines={lines} onChange={setTo} placeholder={t.destination}/>{same&&<Text style={[styles.error,{color:theme.colors.danger}]}>{t.same}</Text>}
   {transport==='metro'&&<><Text style={[styles.preferenceLabel,{color:theme.colors.muted}]}>{t.plan}</Text><View style={styles.preferences}>{([['fast',t.fastest],['transfers',t.fewer]] as const).map(([value,label])=><Pressable key={value} onPress={()=>setMode(value)} style={[styles.preference,{borderColor:mode===value?theme.colors.accent:theme.colors.border,backgroundColor:mode===value?theme.colors.accentSoft:theme.colors.surface}]}><Text style={{color:mode===value?theme.colors.accent:theme.colors.muted,fontWeight:'800'}}>{label}</Text></Pressable>)}</View></>}
   <Pressable disabled={!ready} onPress={search} style={[styles.search,{backgroundColor:theme.colors.dark,opacity:ready?1:.4}]}><Text style={styles.searchText}>{t.find}</Text><Text style={styles.searchText}>→</Text></Pressable>
  </View>
  <View style={[styles.info,{backgroundColor:themeMode==='dark'?'#20362D':'#EEF2EC'}]}><Text style={styles.infoIcon}>⌁</Text><View style={{flex:1}}><Text style={[styles.infoTitle,{color:theme.colors.text}]}>{t.offline}</Text><Text style={[styles.infoCopy,{color:theme.colors.muted}]}>{t.serviceCopy}</Text></View></View><Text style={[styles.version,{color:theme.colors.muted}]}>{t.version}</Text>
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:20,paddingBottom:48},brandRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:4,marginBottom:13,gap:12},brand:{fontSize:19,fontWeight:'900'},offline:{paddingHorizontal:10,paddingVertical:6,borderRadius:99},offlineText:{fontSize:9,fontWeight:'900',letterSpacing:.8},quickNav:{flexDirection:'row',gap:14,marginBottom:34},quickNavText:{fontSize:12,fontWeight:'800'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.35,marginBottom:9},title:{fontSize:35,lineHeight:40,fontWeight:'900',letterSpacing:-1.1},copy:{fontSize:16,lineHeight:23,marginTop:16,marginBottom:28},tabs:{flexDirection:'row',borderRadius:16,padding:4,marginBottom:14},tab:{flex:1,paddingVertical:12,alignItems:'center',borderRadius:13},tabText:{fontSize:14,fontWeight:'800'},card:{borderRadius:28,padding:20,borderWidth:1},cardTitle:{fontSize:25,fontWeight:'900',marginTop:1},swap:{alignSelf:'center',marginTop:13,paddingHorizontal:14,paddingVertical:9,borderWidth:1,borderRadius:99},error:{fontSize:13,fontWeight:'700',marginTop:12},preferenceLabel:{fontSize:13,fontWeight:'700',marginTop:22,marginBottom:8},preferences:{flexDirection:'row',gap:8},preference:{flex:1,paddingVertical:12,paddingHorizontal:8,borderRadius:14,borderWidth:1,alignItems:'center'},search:{height:58,borderRadius:17,marginTop:22,paddingHorizontal:18,alignItems:'center',justifyContent:'space-between',flexDirection:'row'},searchText:{color:'#fff',fontSize:16,fontWeight:'900'},info:{marginTop:16,borderRadius:20,padding:18,flexDirection:'row',gap:14},infoIcon:{fontSize:24},infoTitle:{fontSize:14,fontWeight:'900'},infoCopy:{fontSize:13,lineHeight:19,marginTop:3},version:{textAlign:'center',fontSize:9,fontWeight:'900',letterSpacing:1.6,marginTop:30}});
