import { useMemo, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import * as Speech from 'expo-speech';
import { SafeAreaView } from 'react-native-safe-area-context';
import { metroLines, metrobusLines, planRoute, type RouteMode, type TransitRoute, type Transport } from '@meperdienelmetro/core';
import { useApp } from '../src/app-state';
import { TransitMap } from '../src/components/TransitMap';

function routeNarration(route:TransitRoute,from:string,to:string,language:string){const steps=route.segments.map((segment,index)=>`${index?` ${language==='es'?'Después transborda':'Then transfer'} ${language==='es'?'en':'at'} ${segment.stations[0]}.`:''} ${language==='es'?'Toma':'Take'} ${language==='es'?'la línea':'line'} ${segment.line.id}, ${language==='es'?'dirección':'towards'} ${segment.direction}. ${language==='es'?'Recorre':'Travel'} ${segment.stations.length-1} ${language==='es'?'estaciones':'stops'}.`).join('');return language==='es'?`Ruta de ${from} a ${to}. Duración estimada ${route.minutes} minutos.${steps} Llegaste a ${to}.`:`Route from ${from} to ${to}. Estimated duration ${route.minutes} minutes.${steps} You arrived at ${to}.`;}

export default function RouteScreen(){
 const {theme,t,language,systemName}=useApp(); const params=useLocalSearchParams<{transport:string;from:string;to:string;mode:string}>(); const transport=(params.transport==='metrobus'?'metrobus':'metro') as Transport; const mode=(params.mode==='transfers'?'transfers':'fast') as RouteMode; const from=params.from||'';const to=params.to||'';
 const routes=useMemo(()=>planRoute({transport,from,to,mode}).routes,[transport,from,to,mode]);const [selected,setSelected]=useState(0);const route=routes[selected]||routes[0];const lines=transport==='metro'?metroLines:metrobusLines;
 const share=async()=>{if(!route)return;await Share.share({message:`${t.route}: ${from} → ${to}. ${route.minutes} ${t.minutes}, ${route.stops} ${t.stops}, ${route.transfers} ${t.transfers}.`});};
 const speak=()=>{if(route)Speech.speak(routeNarration(route,from,to,language),{language:language==='es'?'es-MX':'en-US',rate:.92});};
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.colors.background}]}><ScrollView contentContainerStyle={styles.page}>
  <View style={styles.topbar}><Pressable onPress={()=>{Speech.stop();router.back()}} style={[styles.back,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Text style={[styles.backText,{color:theme.colors.text}]}>←</Text></Pressable><Text style={[styles.topTitle,{color:theme.colors.text}]}>{t.route}</Text><View style={{width:42}}/></View>
  <Text style={[styles.eyebrow,{color:theme.colors.accent}]}>{systemName(transport)}</Text><Text style={[styles.title,{color:theme.colors.text}]}>{from}</Text><Text style={[styles.to,{color:theme.colors.muted}]}>→ {to}</Text>
  {!route?<View style={[styles.empty,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Text style={[styles.emptyTitle,{color:theme.colors.text}]}>{t.noRoute}</Text><Text style={[styles.emptyCopy,{color:theme.colors.muted}]}>{t.retry}</Text></View>:<>
   {routes.length>1&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.options}>{routes.map((item,index)=><Pressable key={index} onPress={()=>setSelected(index)} style={[styles.option,{backgroundColor:selected===index?theme.colors.accentSoft:theme.colors.surface,borderColor:selected===index?theme.colors.accent:theme.colors.border}]}><Text style={{fontWeight:'900',color:selected===index?theme.colors.accent:theme.colors.text}}>{index===0?t.recommended:`${t.alternative} ${index}`}</Text><Text style={[styles.optionMeta,{color:theme.colors.muted}]}>{item.minutes} {t.minutes} · {item.transfers} {t.transfers}</Text></Pressable>)}</ScrollView>}
   <View style={[styles.actions,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><Pressable onPress={share} style={[styles.action,{borderColor:theme.colors.border}]} accessibilityRole="button" accessibilityLabel={t.share}><Text style={{color:theme.colors.text}}>↗ {t.share}</Text></Pressable><Pressable onPress={speak} style={[styles.iconAction,{borderColor:theme.colors.border}]} accessibilityRole="button" accessibilityLabel={t.listen}><Text style={[styles.actionIcon,{color:theme.colors.text}]}>▶</Text></Pressable><Pressable onPress={()=>Speech.stop()} style={styles.iconAction} accessibilityRole="button" accessibilityLabel={t.stopAudio}><Text style={[styles.actionIcon,{color:theme.colors.accent}]}>■</Text></Pressable></View>
   <View style={[styles.stats,{backgroundColor:theme.colors.dark}]}>{[[`${route.minutes}`,t.minutes], [`${route.stops}`,t.stops], [`${route.transfers}`,t.transfers]].map(([value,label])=><View style={styles.stat} key={label}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View>
   <TransitMap lines={lines} route={route} title={t.routeMap}/>
   <Text style={[styles.sectionTitle,{color:theme.colors.text}]}>{t.steps}</Text><View style={styles.timeline}>{route.segments.map((segment,index)=><View key={`${segment.line.id}-${index}`} style={[styles.segment,{backgroundColor:theme.colors.surface,borderColor:theme.colors.border}]}><View style={[styles.lineBadge,{backgroundColor:segment.line.color}]}><Text style={styles.lineBadgeText}>{segment.line.id}</Text></View><View style={{flex:1}}><Text style={[styles.segmentTitle,{color:theme.colors.text}]}>{t.line} {segment.line.id} · {t.direction} {segment.direction}</Text><Text style={[styles.segmentMeta,{color:theme.colors.muted}]}>{segment.stations.length-1} {t.stops}</Text>{segment.stations.map((station,stationIndex)=><View key={`${station}-${stationIndex}`} style={styles.stationRow}><View style={styles.railWrap}><View style={[styles.dot,{borderColor:segment.line.color}]}/>{stationIndex<segment.stations.length-1&&<View style={[styles.rail,{backgroundColor:segment.line.color}]}/>}</View><View style={{flex:1,paddingBottom:13}}><Text style={[styles.stationText,{color:stationIndex===0||stationIndex===segment.stations.length-1?theme.colors.text:theme.colors.muted,fontWeight:stationIndex===0||stationIndex===segment.stations.length-1?'900':'500'}]}>{station}</Text>{stationIndex===0&&<Text style={[styles.hint,{color:theme.colors.accent}]}>{t.board}</Text>}{stationIndex===segment.stations.length-1&&<Text style={[styles.hint,{color:theme.colors.accent}]}>{index===route.segments.length-1?t.arrived:t.transfer}</Text>}</View></View>)}</View></View>)}</View>
  </>}
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:20,paddingBottom:52},topbar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:28},back:{width:42,height:42,borderRadius:21,borderWidth:1,alignItems:'center',justifyContent:'center'},backText:{fontSize:22},topTitle:{fontSize:15,fontWeight:'900'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{fontSize:30,fontWeight:'900',marginTop:8},to:{fontSize:24,fontWeight:'700',marginBottom:20},options:{gap:8,paddingBottom:13},option:{minWidth:160,padding:14,borderWidth:1,borderRadius:16},optionMeta:{fontSize:11,marginTop:4},actions:{flexDirection:'row',borderWidth:1,borderRadius:16,overflow:'hidden',marginBottom:12},action:{flex:1,padding:12,borderRightWidth:1,alignItems:'center',justifyContent:'center'},iconAction:{width:58,padding:12,borderRightWidth:1,alignItems:'center',justifyContent:'center'},actionIcon:{fontSize:18,fontWeight:'900'},stats:{flexDirection:'row',borderRadius:22,paddingVertical:18,marginBottom:4},stat:{flex:1,alignItems:'center'},statValue:{fontSize:24,fontWeight:'900',color:'#fff'},statLabel:{fontSize:10,color:'#C7D8D0',marginTop:3},sectionTitle:{fontSize:25,fontWeight:'900',marginTop:30,marginBottom:15},timeline:{gap:12},segment:{borderRadius:22,borderWidth:1,padding:16,flexDirection:'row',gap:12},lineBadge:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center'},lineBadgeText:{color:'#fff',fontWeight:'900'},segmentTitle:{fontSize:14,fontWeight:'900',lineHeight:20},segmentMeta:{fontSize:12,marginTop:2,marginBottom:14},stationRow:{flexDirection:'row',minHeight:42},railWrap:{width:22,alignItems:'center'},dot:{width:11,height:11,borderRadius:6,borderWidth:3,backgroundColor:'#fff',zIndex:1},rail:{width:3,flex:1,marginTop:-1},stationText:{fontSize:13,paddingLeft:7},hint:{fontSize:10,fontWeight:'800',paddingLeft:7,marginTop:2},empty:{borderWidth:1,borderRadius:22,padding:28,alignItems:'center'},emptyTitle:{fontSize:19,fontWeight:'900'},emptyCopy:{fontSize:14,marginTop:6,textAlign:'center'}});
