import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import type { TransitLine } from '@meperdienelmetro/core';
import { useApp } from '../app-state';

export function StationDetail({station,lines,onClose}:{station:string|null;lines:TransitLine[];onClose:()=>void}){
 const {theme,t}=useApp(); if(!station)return null;
 return <Modal visible transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><Pressable style={[styles.sheet,{backgroundColor:theme.colors.surface}]} onPress={event=>event.stopPropagation()}><View style={[styles.mark,{borderColor:lines[0]?.color??theme.colors.accent}]}><Text style={[styles.markText,{color:lines[0]?.color??theme.colors.accent}]}>{station.slice(0,2).toUpperCase()}</Text></View><Text style={[styles.eyebrow,{color:theme.colors.accent}]}>{t.station}</Text><Text style={[styles.name,{color:theme.colors.text}]}>{station}</Text><Text style={[styles.copy,{color:theme.colors.muted}]}>{lines.length>1?`${t.connections}: ${lines.length}`:`${t.line} ${lines[0]?.id??''}`}</Text><View style={styles.badges}>{lines.map(line=><View key={line.id} style={[styles.badge,{backgroundColor:line.color}]}><Text style={styles.badgeText}>{t.line} {line.id}</Text></View>)}</View><Pressable style={[styles.close,{borderColor:theme.colors.border}]} onPress={onClose}><Text style={{color:theme.colors.text}}>{t.close}</Text></Pressable></Pressable></Pressable></Modal>;
}
const styles=StyleSheet.create({backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'#00000070'},sheet:{borderTopLeftRadius:28,borderTopRightRadius:28,padding:24,alignItems:'flex-start'},mark:{width:62,height:62,borderRadius:18,borderWidth:3,alignItems:'center',justifyContent:'center',marginBottom:18},markText:{fontSize:19,fontWeight:'900'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.2},name:{fontSize:28,fontWeight:'900',marginTop:5},copy:{fontSize:14,marginTop:7},badges:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:18},badge:{paddingHorizontal:10,paddingVertical:6,borderRadius:99},badgeText:{color:'#fff',fontWeight:'800',fontSize:12},close:{alignSelf:'stretch',alignItems:'center',paddingVertical:14,borderWidth:1,borderRadius:14,marginTop:22}});
